name: LitLibs
version: '${project.version}'
main: me.waterarchery.litlibs.LitLibsPlugin
api-version: '1.13'
author: WaterArchery
softdepend:
  - BentoBox
  - SuperiorSkyblock2
  - Lands
  - DecentHolograms
  - CMI
  - HolographicDisplays
  - PlaceholderAPI
  - Essentials
  - ShopGUIPlus
  - EconomyShopGUI